---
- name: Check CVE-2025-26465 and CVE-2025-26466 
  hosts: all
  gather_facts: true
  tasks:
    - name: Check installed openssh-server version on Ubuntu
      when: >
        ansible_distribution == "Ubuntu"
      block:
        - name: Get installed ssh version
          ansible.builtin.shell: apt list --installed | grep openssh-server
          register: openssh_server_version
        - name: Set fact with current version
          set_fact:
            cve_check_result: >
              Hostname: {{ ansible_hostname }},
              IP: {{ ansible_default_ipv4.address }},
              OS: {{ ansible_distribution }} {{ ansible_distribution_version }},
              Installed-Package: {{ openssh_server_version.stdout | default('not found') }}
    - name: Check VerifyHostKeyDNS on RockyLinux
      when: >
        ansible_distribution == "Rocky"
      block:
        - name: Get VerifyHostKeyDNS configuration
          ansible.builtin.shell: ssh -G localhost | grep verifyhostkeydns
          register: verify_host_key_dns_status
        - name: Set fact with current status
          set_fact:
            cve_check_result: >
              Hostname: {{ ansible_hostname }},
              IP: {{ ansible_default_ipv4.address }},
              OS: {{ ansible_distribution }} {{ ansible_distribution_version }},
              VerifyHostKeyDNS-Configuration: {{ verify_host_key_dns_status.stdout | default('not found') }}

- name: Save the report to localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Write header
      copy:
        dest: /tmp/report.txt
        content: "--- CVE-2025-26465 & CVE-2025-26466 ---\n\n"
        force: true

    - name: Append each host's result to the report
      lineinfile:
        path: /tmp/report.txt
        line: "{{ hostvars[item].cve_check_result | default('No result from host: ' ~ item) }}"
        create: yes
        insertafter: EOF
      loop: "{{ groups['all'] }}"
